#!/bin/bash

# variables
RC_PROJECT=rc_unimog_control_group2

SCRIPT_HOST_AVAILABLE=$FINROC_HOME/sources/cpp/projects/rc_unimog/scripts/host_available
HOST_PI=rc-unimog-pi
HOST_JETSON=jetson

SCRIPT_IS_HARDWARE="$SCRIPT_HOST_AVAILABLE $HOST_JETSON"
SCRIPT_PI_AVAILABLE="$SCRIPT_HOST_AVAILABLE $HOST_PI"

# check whether this script is running on the hardware
echo "Detecting Hardware"
if $SCRIPT_IS_HARDWARE
then
  echo "Unimog Hardware detected"
  # wait until the pi is registered at the jetson
  echo "Wait for the pi to be available"
  while ! $SCRIPT_PI_AVAILABLE;
  do
    echo "Waiting ..."
    sleep 1s
  done
  echo "Pi available"
  PART_OPTION="--connect=$HOST_PI:4443 -m hardware"
else
  echo "Control not running on the hardware, choosing Simulation"
  PART_OPTION="-m unreal"
fi

# start the control part
echo "Starting Control Part"
cd $FINROC_HOME
source scripts/setenv -p $RC_PROJECT
PART_COMMAND="$RC_PROJECT $PART_OPTION -c $FINROC_PROJECT_HOME/etc/config.xml"
echo "Running $PART_COMMAND"
$PART_COMMAND

# done
echo "Exit"
